/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cn;

import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

import net.proteanit.sql.DbUtils;
/**
 *
 * @author osman
 */

public class Frm_Venue extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Venue
     */
    
    String name;
    
    public String getName()
    {
        return name;
    }
    
    public void updateMayor(ResultSet rs)
    {
      // leaderBoard.setEnabled(true);
       leaderBoard.setModel(DbUtils.resultSetToTableModel(rs));
      // leaderBoard.setEnabled(false);
        
    }
    public Frm_Venue(String id) throws Exception {
        
        initComponents();
        name=id;
        try
        {
            int l=360;
            int h=360;
            int limit=100;
            
            this.setPreferredSize(new java.awt.Dimension(l, h));
            this.setMaximumSize(new java.awt.Dimension(l, h));
            this.setMinimumSize(new java.awt.Dimension(l, h));
            
            lblTitle.setText(Location.getName(id));
            new Timer(this).start();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "In Frm_Venu: "+e.getMessage());
        }
        

        
        
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        leaderBoard = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        leaderBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Check-Ins"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(leaderBoard);
        leaderBoard.getColumnModel().getColumn(0).setResizable(false);
        leaderBoard.getColumnModel().getColumn(1).setResizable(false);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 310, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Leaderboard");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 310, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 70, 360, 10);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("PLACE NAME");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(10, 20, 330, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable leaderBoard;
    // End of variables declaration//GEN-END:variables
}
